spring:
  application:
  name: ctsj-main
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///my_community
    username: root
    password: 123456

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:11010/eureka/

# 映射文件位置
mybatis:
  mapper-locations:
        - classpath:mapper/*Mapper.xml
        - classpath:mybatis-config.xml
  configuration:
    map-underscore-to-camel-case: true #驼峰
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org.mybatis: DEBUG

---
server:
  port: 9009
spring:
  profiles: user1







