spring:
  application:
    name: ctsj-index
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///my_community
    username: root
    password: 123456

server:
  port: 8089

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true


