spring:
  application:
     name: ctsj-eureka

server:
  port: 11010

eureka:
  client:
    # ????????? eureka ?????, ??eureka???
    # ??????
    registerWithEureka: false
    # ??????
    fetchRegistry: false