#spring:
#  application:
#   name: ctsj-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:11010/eureka/

server:
  port: 9999

spring:
  application:
    name: ctsj-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: wghello
          uri: https://www.hnit.edu.cn
          predicates:
            - Path=/test/{segment}
          filters:
            #            - RewritePath=/test/(?<segment>.*), /demo/$\{segment}
            - SetPath=/demo/{segment}

        - id: test
          uri: https://www.baidu.com
          predicates:
            - Path=/way/**
          filters:
            - RewritePath=/way/(?<segment>.*), /$\{segment}

        - id: default
          uri: https://www.hnit.edu.cn
          predicates:
            - Path=/**

